# Generated by Django 5.1.6 on 2025-02-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10)),
                ('telefone', models.CharField(blank=True, max_length=9, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('data_diagnostico', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
